from src.modules.agent_registry.schemas import BuildAgentRegistryEntryInput, BuildAgentRegistryRequest
from src.shared.enums import (
    AgentKind,
    AgentScope,
    CompanyAgentActivationState,
    DataPolicy,
    ModelTier,
    RuntimeMode,
)

COMPANY_AGENTS: list[BuildAgentRegistryEntryInput] = [
    BuildAgentRegistryEntryInput(
        agent_key="A00",
        agent_label="Chief of Staff",
        agent_role_name="Chief of Staff",
        owner_role="CEO",
        reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.ACTIVE_METADATA_ONLY,
        agent_scope=AgentScope.COMPANY_OPERATIONS,
        agent_kind=AgentKind.OPERATING_SYSTEM,
        reports_to="CEO",
        data_policy=DataPolicy.LOCAL_FIRST,
        runtime_mode=RuntimeMode.MANUAL_CONTEXT_ONLY,
        model_tier=ModelTier.REASONING,
        description="Coordinates Arvectum internal company-agent system. Converts CEO intent into structured work, assigns tasks to specialist agents, monitors status, detects blockers, and prepares CEO decision memos.",
        responsibilities=[
            "Decompose CEO goals into agent-assigned tasks",
            "Assign agents to tasks",
            "Track execution status",
            "Detect blockers",
            "Request missing information",
            "Prepare CEO memos",
            "Maintain operating rhythm",
        ],
        inputs=[
            "CEO instruction",
            "Agent reports",
            "Project status",
            "Task logs",
            "System events",
        ],
        outputs=[
            "Daily memo",
            "Weekly memo",
            "Task routing plan",
            "Escalation memo",
            "Unresolved decision list",
        ],
        escalation_rules=[
            "Escalate when task affects money",
            "Escalate when task affects contracts",
            "Escalate when task affects client promises",
            "Escalate when task affects production deployment",
            "Escalate when task affects legal risk",
            "Escalate when task affects reputation",
            "Escalate when task affects confidential data boundaries",
        ],
        forbidden_actions=[
            "Do not approve contracts",
            "Do not commit company funds",
            "Do not send external messages without explicit approval",
            "Do not expose confidential data to cloud models",
            "Do not perform autonomous execution",
            "Do not overwrite source-of-truth records without confirmation",
        ],
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A10",
        agent_label="Tender Operator",
        agent_role_name="Tender Operator",
        owner_role="A00",
        reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.ACTIVE_METADATA_ONLY,
        agent_scope=AgentScope.COMPANY_OPERATIONS,
        agent_kind=AgentKind.TENDER_OPERATIONS,
        reports_to="A00",
        data_policy=DataPolicy.LOCAL_ONLY,
        runtime_mode=RuntimeMode.MANUAL_CONTEXT_ONLY,
        model_tier=ModelTier.REASONING,
        description="Coordinates tender workflow from intake to bid/no-bid recommendation. Works with requirements, RFQ, supplier quotes, risk notes, finance notes, bid package status, and CEO decision memos.",
        responsibilities=[
            "Coordinate tender workflow from intake to bid/no-bid",
            "Gather requirements and RFQ data",
            "Collect supplier quotes",
            "Integrate risk and finance notes",
            "Track bid package status",
            "Prepare CEO decision memos",
        ],
        inputs=[
            "Tender intake documents",
            "RFQ drafts",
            "Supplier quotes",
            "Risk notes from A21",
            "Finance notes from A20",
            "CEO instructions",
        ],
        outputs=[
            "Tender status report",
            "Bid/no-bid recommendation",
            "CEO decision memo draft",
            "Escalation note",
        ],
        escalation_rules=[
            "Escalate when tender value exceeds threshold",
            "Escalate when risk notes indicate deal_breaker_candidate",
            "Escalate when finance notes indicate negative margin",
            "Escalate when deadline is at risk",
        ],
        forbidden_actions=[
            "Do not submit bids without CEO approval",
            "Do not commit company to tender obligations",
            "Do not share tender data externally",
        ],
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A11",
        agent_label="RFQ & Supplier Analyst",
        agent_role_name="RFQ & Supplier Analyst",
        owner_role="A10",
        reviewer_role="A00",
        activation_state=CompanyAgentActivationState.ACTIVE_METADATA_ONLY,
        agent_scope=AgentScope.COMPANY_OPERATIONS,
        agent_kind=AgentKind.TENDER_OPERATIONS,
        reports_to="A10",
        data_policy=DataPolicy.LOCAL_ONLY,
        runtime_mode=RuntimeMode.MANUAL_CONTEXT_ONLY,
        model_tier=ModelTier.STANDARD,
        description="Prepares supplier questions, RFQ drafts, normalizes supplier quotes, compares commercial terms, and identifies missing or inconsistent supplier information.",
        responsibilities=[
            "Prepare supplier questions",
            "Draft RFQ documents",
            "Normalize supplier quotes",
            "Compare commercial terms",
            "Identify missing or inconsistent supplier information",
        ],
        inputs=[
            "Tender requirements",
            "Supplier list",
            "Previous RFQ templates",
            "Supplier responses",
        ],
        outputs=[
            "RFQ draft",
            "Supplier comparison memo",
            "Missing information report",
        ],
        escalation_rules=[
            "Escalate when supplier data is inconsistent",
            "Escalate when critical information is missing",
        ],
        forbidden_actions=[
            "Do not contact suppliers directly",
            "Do not commit to supplier terms",
        ],
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A20",
        agent_label="Finance & Unit Economics",
        agent_role_name="Finance & Unit Economics",
        owner_role="CEO",
        reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.ACTIVE_METADATA_ONLY,
        agent_scope=AgentScope.COMPANY_OPERATIONS,
        agent_kind=AgentKind.RISK_FINANCE_LEGAL,
        reports_to="CEO",
        data_policy=DataPolicy.LOCAL_ONLY,
        runtime_mode=RuntimeMode.MANUAL_CONTEXT_ONLY,
        model_tier=ModelTier.REASONING,
        description="Evaluates deal economics, margin, cash gap, payment timing, financing needs, downside scenarios, and financial feasibility before CEO commitment.",
        responsibilities=[
            "Evaluate deal economics and margin",
            "Analyze cash gap and payment timing",
            "Assess financing needs",
            "Model downside scenarios",
            "Determine financial feasibility",
        ],
        inputs=[
            "Tender cost breakdown",
            "Supplier quotes",
            "Payment terms",
            "Company financial position",
        ],
        outputs=[
            "Finance memo",
            "Unit economics report",
            "Cash gap analysis",
            "Downside scenario summary",
        ],
        escalation_rules=[
            "Escalate when margin is negative",
            "Escalate when cash gap exceeds available resources",
            "Escalate when payment terms are unfavorable",
        ],
        forbidden_actions=[
            "Do not approve expenditures",
            "Do not commit company funds",
            "Do not share financial data externally",
        ],
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A21",
        agent_label="Legal & Contract Risk",
        agent_role_name="Legal & Contract Risk",
        owner_role="CEO",
        reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.ACTIVE_METADATA_ONLY,
        agent_scope=AgentScope.COMPANY_OPERATIONS,
        agent_kind=AgentKind.RISK_FINANCE_LEGAL,
        reports_to="CEO",
        data_policy=DataPolicy.LOCAL_ONLY,
        runtime_mode=RuntimeMode.MANUAL_CONTEXT_ONLY,
        model_tier=ModelTier.REASONING,
        description="Analyzes contracts, tender conditions, liability clauses, penalties, deadlines, acceptance conditions, unilateral rights, and classifies risks.",
        responsibilities=[
            "Analyze contracts and tender conditions",
            "Review liability clauses and penalties",
            "Assess deadlines and acceptance conditions",
            "Identify unilateral rights",
            "Classify risks as market_standard_harsh_term, commercially_material_risk, or deal_breaker_candidate",
        ],
        inputs=[
            "Contract drafts",
            "Tender conditions",
            "Legal templates",
            "Regulatory requirements",
        ],
        outputs=[
            "Contract risk memo",
            "Risk classification report",
            "Escalation note for deal_breaker_candidate",
        ],
        escalation_rules=[
            "Escalate when risk is classified as deal_breaker_candidate",
            "Escalate when liability clauses are unusual",
            "Escalate when penalties exceed threshold",
        ],
        forbidden_actions=[
            "Do not sign contracts",
            "Do not commit company legally",
            "Do not share legal analysis externally",
        ],
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A40",
        agent_label="CTO / System Architect",
        agent_role_name="CTO / System Architect",
        owner_role="CEO",
        reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.ACTIVE_METADATA_ONLY,
        agent_scope=AgentScope.COMPANY_OPERATIONS,
        agent_kind=AgentKind.ENGINEERING,
        reports_to="CEO",
        data_policy=DataPolicy.LOCAL_FIRST,
        runtime_mode=RuntimeMode.MANUAL_CONTEXT_ONLY,
        model_tier=ModelTier.CODE_REASONING,
        description="Maintains technical coherence of Arvectum systems: architecture, APIs, database schema, integrations, security boundaries, local LLM architecture, and technical roadmap.",
        responsibilities=[
            "Maintain system architecture",
            "Design APIs and database schema",
            "Manage integrations",
            "Enforce security boundaries",
            "Design local LLM architecture",
            "Maintain technical roadmap",
        ],
        inputs=[
            "Product requirements",
            "Technical debt reports",
            "Security audit findings",
            "Infrastructure status",
        ],
        outputs=[
            "Architecture decision records",
            "Technical roadmap updates",
            "Security boundary documentation",
            "Integration specifications",
        ],
        escalation_rules=[
            "Escalate when security boundaries are at risk",
            "Escalate when technical debt exceeds threshold",
            "Escalate when architecture decisions affect multiple modules",
        ],
        forbidden_actions=[
            "Do not deploy to production without QA approval",
            "Do not expose secrets or keys",
            "Do not make unilateral architecture changes",
        ],
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A42",
        agent_label="QA & Release",
        agent_role_name="QA & Release",
        owner_role="A40",
        reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.ACTIVE_METADATA_ONLY,
        agent_scope=AgentScope.COMPANY_OPERATIONS,
        agent_kind=AgentKind.ENGINEERING,
        reports_to="A40",
        data_policy=DataPolicy.LOCAL_ONLY,
        runtime_mode=RuntimeMode.MANUAL_CONTEXT_ONLY,
        model_tier=ModelTier.STANDARD,
        description="Verifies that Arvectum software is actually ready for pilot, release, or client demo: tests, smoke checks, release checks, documentation, known risks, and rollback readiness.",
        responsibilities=[
            "Run tests and smoke checks",
            "Perform release readiness verification",
            "Verify documentation completeness",
            "Track known risks",
            "Assess rollback readiness",
        ],
        inputs=[
            "Release candidates",
            "Test results",
            "Documentation status",
            "Known issues list",
        ],
        outputs=[
            "QA readiness memo",
            "Release checklist status",
            "Known risks report",
            "Rollback readiness assessment",
        ],
        escalation_rules=[
            "Escalate when critical tests fail",
            "Escalate when release blockers are found",
            "Escalate when documentation is incomplete",
        ],
        forbidden_actions=[
            "Do not approve releases without passing checks",
            "Do not hide test failures",
            "Do not skip smoke checks",
        ],
    ),
]

INACTIVE_AGENTS: list[BuildAgentRegistryEntryInput] = [
    BuildAgentRegistryEntryInput(
        agent_key="A01", agent_label="Product Architect", agent_role_name="Product Architect",
        owner_role="CEO", reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.INACTIVE,
        agent_scope=AgentScope.COMPANY_OPERATIONS, agent_kind=AgentKind.OPERATING_SYSTEM,
        reports_to="CEO", data_policy=DataPolicy.LOCAL_FIRST, runtime_mode=RuntimeMode.METADATA_ONLY,
        model_tier=ModelTier.REASONING,
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A02", agent_label="Business Model", agent_role_name="Business Model",
        owner_role="CEO", reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.INACTIVE,
        agent_scope=AgentScope.COMPANY_OPERATIONS, agent_kind=AgentKind.GROWTH,
        reports_to="CEO", data_policy=DataPolicy.LOCAL_ONLY, runtime_mode=RuntimeMode.METADATA_ONLY,
        model_tier=ModelTier.REASONING,
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A03", agent_label="Research & Knowledge", agent_role_name="Research & Knowledge",
        owner_role="CEO", reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.DRAFT,
        agent_scope=AgentScope.COMPANY_OPERATIONS, agent_kind=AgentKind.RESEARCH,
        reports_to="CEO", data_policy=DataPolicy.LOCAL_FIRST, runtime_mode=RuntimeMode.METADATA_ONLY,
        model_tier=ModelTier.STANDARD,
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A12", agent_label="Supplier Relations", agent_role_name="Supplier Relations",
        owner_role="A10", reviewer_role="A00",
        activation_state=CompanyAgentActivationState.INACTIVE,
        agent_scope=AgentScope.COMPANY_OPERATIONS, agent_kind=AgentKind.TENDER_OPERATIONS,
        reports_to="A10", data_policy=DataPolicy.LOCAL_ONLY, runtime_mode=RuntimeMode.METADATA_ONLY,
        model_tier=ModelTier.STANDARD,
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A13", agent_label="Bid Package", agent_role_name="Bid Package",
        owner_role="A10", reviewer_role="A00",
        activation_state=CompanyAgentActivationState.INACTIVE,
        agent_scope=AgentScope.COMPANY_OPERATIONS, agent_kind=AgentKind.TENDER_OPERATIONS,
        reports_to="A10", data_policy=DataPolicy.LOCAL_ONLY, runtime_mode=RuntimeMode.METADATA_ONLY,
        model_tier=ModelTier.STANDARD,
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A22", agent_label="Compliance & Evidence", agent_role_name="Compliance & Evidence",
        owner_role="CEO", reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.DRAFT,
        agent_scope=AgentScope.COMPANY_OPERATIONS, agent_kind=AgentKind.RISK_FINANCE_LEGAL,
        reports_to="CEO", data_policy=DataPolicy.LOCAL_ONLY, runtime_mode=RuntimeMode.METADATA_ONLY,
        model_tier=ModelTier.STANDARD,
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A30", agent_label="Client Success", agent_role_name="Client Success",
        owner_role="CEO", reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.DRAFT,
        agent_scope=AgentScope.COMPANY_OPERATIONS, agent_kind=AgentKind.DELIVERY,
        reports_to="CEO", data_policy=DataPolicy.LOCAL_ONLY, runtime_mode=RuntimeMode.METADATA_ONLY,
        model_tier=ModelTier.STANDARD,
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A31", agent_label="Delivery Manager", agent_role_name="Delivery Manager",
        owner_role="CEO", reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.DRAFT,
        agent_scope=AgentScope.COMPANY_OPERATIONS, agent_kind=AgentKind.DELIVERY,
        reports_to="CEO", data_policy=DataPolicy.LOCAL_ONLY, runtime_mode=RuntimeMode.METADATA_ONLY,
        model_tier=ModelTier.STANDARD,
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A32", agent_label="Support", agent_role_name="Support",
        owner_role="A31", reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.DRAFT,
        agent_scope=AgentScope.COMPANY_OPERATIONS, agent_kind=AgentKind.DELIVERY,
        reports_to="A31", data_policy=DataPolicy.LOCAL_ONLY, runtime_mode=RuntimeMode.METADATA_ONLY,
        model_tier=ModelTier.STANDARD,
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A41", agent_label="Backend Engineer", agent_role_name="Backend Engineer",
        owner_role="A40", reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.INACTIVE,
        agent_scope=AgentScope.COMPANY_OPERATIONS, agent_kind=AgentKind.ENGINEERING,
        reports_to="A40", data_policy=DataPolicy.LOCAL_ONLY, runtime_mode=RuntimeMode.METADATA_ONLY,
        model_tier=ModelTier.CODE_REASONING,
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A43", agent_label="DevOps / Local Infra", agent_role_name="DevOps / Local Infra",
        owner_role="A40", reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.DRAFT,
        agent_scope=AgentScope.COMPANY_OPERATIONS, agent_kind=AgentKind.ENGINEERING,
        reports_to="A40", data_policy=DataPolicy.LOCAL_ONLY, runtime_mode=RuntimeMode.METADATA_ONLY,
        model_tier=ModelTier.CODE_REASONING,
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A50", agent_label="Sales Development", agent_role_name="Sales Development",
        owner_role="CEO", reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.DRAFT,
        agent_scope=AgentScope.COMPANY_OPERATIONS, agent_kind=AgentKind.GROWTH,
        reports_to="CEO", data_policy=DataPolicy.LOCAL_ONLY, runtime_mode=RuntimeMode.METADATA_ONLY,
        model_tier=ModelTier.WRITING,
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A51", agent_label="Marketing & Brand", agent_role_name="Marketing & Brand",
        owner_role="CEO", reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.DRAFT,
        agent_scope=AgentScope.COMPANY_OPERATIONS, agent_kind=AgentKind.GROWTH,
        reports_to="CEO", data_policy=DataPolicy.HYBRID_PUBLIC_ONLY, runtime_mode=RuntimeMode.METADATA_ONLY,
        model_tier=ModelTier.WRITING,
    ),
    BuildAgentRegistryEntryInput(
        agent_key="A52", agent_label="Proposal / Commercial Docs", agent_role_name="Proposal / Commercial Docs",
        owner_role="A50", reviewer_role="CEO",
        activation_state=CompanyAgentActivationState.DRAFT,
        agent_scope=AgentScope.COMPANY_OPERATIONS, agent_kind=AgentKind.GROWTH,
        reports_to="A50", data_policy=DataPolicy.LOCAL_ONLY, runtime_mode=RuntimeMode.METADATA_ONLY,
        model_tier=ModelTier.WRITING,
    ),
]


def build_company_agent_registry_request() -> BuildAgentRegistryRequest:
    return BuildAgentRegistryRequest(
        registry_scope="COMPANY_OPERATIONS",
        entries=COMPANY_AGENTS + INACTIVE_AGENTS,
    )


def get_active_company_agents() -> list[BuildAgentRegistryEntryInput]:
    return [a for a in COMPANY_AGENTS if a.activation_state == CompanyAgentActivationState.ACTIVE_METADATA_ONLY]


def get_inactive_company_agents() -> list[BuildAgentRegistryEntryInput]:
    return [a for a in INACTIVE_AGENTS]
