EVENT_CODES = {
    "deal_created",
    "deal_metadata_updated",
    "deal_status_changed",
    "deal_status_transition_blocked",
    "deal_status_override_applied",
    "artifact_created",
    "artifact_version_added",
    "artifact_linked",
    "decision_recorded",
    "tender_intake_received",
    "tender_intake_normalized",
    "tender_intake_linked",
    "tender_intake_failed",
    "document_set_created",
    "document_ingestion_started",
    "document_ingestion_completed",
    "document_ingestion_partial",
    "document_ingestion_failed",
    "tender_summary_build_started",
    "tender_summary_built",
    "tender_summary_failed",
}

DECISION_CODES = {
    "MANUAL_STATUS_OVERRIDE",
    "DEAL_MARKED_REJECTED_EARLY",
    "APPROVE_TO_BID",
    "DECLINE_TO_BID",
}
